sdslabs/Rootex

- Game/Main.cpp
- Game/assets/config/test.lua
- rootex/script/interpreter.cpp
- rootex/script/interpreter.h
Missing functionality from last PR
> Add lua variable loading function

- rootex/core/audio/audio_source.cpp
- rootex/core/audio/audio_system.cpp
> Remove explicit deregistration of derived audio buffers

- CMakeLists.txt
fix for-
```
CMake Error at rootex/CMakeLists.txt:77 (target_precompile_headers):
Unknown CMake command "target_precompile_headers".
```
> update min cmake version

- rootex/os/thread.h
> Remove unnecessary variable

- editor/gui/viewport_dock.cpp
- rootex/core/renderer/index_buffer.cpp
- rootex/core/renderer/index_buffer.h
- rootex/core/renderer/rendering_device.cpp
- rootex/core/renderer/rendering_device.h
- rootex/core/renderer/vertex_buffer.cpp
- rootex/core/renderer/vertex_buffer.h
> Remove raw pointers and add ComPtr<> at all used places

- rootex/framework/components/physics/physics_component.cpp
- rootex/framework/components/physics/physics_component.h
- rootex/framework/systems/physics_system.cpp
- rootex/framework/systems/physics_system.h
> Move physics material to physics system

- rootex/common/common.h
This is was already done, we just had to fix the Release mode behaviors for our print macros (PRINT, ERR, WARN, PANIC)
> Add release build conf

- rootex/framework/components/visual/camera_visual_component.cpp
- rootex/framework/components/visual/diffuse_visual_component.cpp
- rootex/framework/components/visual/diffuse_visual_component.h
- rootex/framework/components/visual/visual_2d_component.cpp
- rootex/framework/components/visual/visual_2d_component.h
- rootex/framework/components/visual/visual_component.cpp
- rootex/framework/components/visual/visual_component.h
> Sets 'IsVisible' for visual component

- rootex/core/renderer/index_buffer.cpp
- rootex/core/renderer/rendering_device.cpp
- rootex/core/renderer/rendering_device.h
- rootex/core/renderer/shader.cpp
- rootex/core/renderer/vertex_buffer.cpp
- rootex/framework/components/physics/physics_component.cpp
- rootex/framework/components/physics/physics_component.h
- rootex/framework/components/physics/sphere_component.cpp
- rootex/framework/systems/physics_system.cpp
- rootex/framework/systems/physics_system.h
> Naming fixes of physics and renderer

- rootex/app/application.cpp
> Fix lua state destructing before physics system

- editor/editor.app.json
- editor/editor.cpp
- editor/editor_application.cpp
- game/game.app.json
- game/game_application.cpp
- rootex/app/application.cpp
- rootex/app/application.h
- rootex/app/application_settings.cpp
- rootex/app/application_settings.h
- rootex/core/resource_file.cpp
- rootex/core/resource_file.h
> Add global settings settable at runtime

- rootex/core/renderer/material.cpp
- rootex/framework/components/visual/cpu_particles_visual_component.cpp
- rootex/framework/components/visual/model_visual_component.cpp
- rootex/framework/components/visual/textured_model_visual_component.cpp
- rootex/framework/components/visual/textured_model_visual_component.h
> fix extra prerender binds and change view, projection bind location

- rootex/framework/components/transform_component.cpp
- rootex/framework/components/transform_component.h
I have added the basic uniform scaling algorithm, division by zero errors and edge cases are to be handled yet.
> implement uniform scaling

- editor/editor.cpp
- editor/editor.h
- game/assets/levels/attenuation_test/entities/Cube #3.entity.json
- rootex/core/renderer/rendering_device.cpp
- rootex/core/renderer/rendering_device.h
- rootex/framework/systems/render_system.cpp
- rootex/framework/systems/render_system.h
Wireframe mode can be enabled from the main menu in the editor.
Go to `View` > `Wireframe Mode` to enable/disable wireframe mode of rendering
> Add wireframe mode in Editor

- rootex/main/window.cpp
Fixed the issue by removing the piece of code that was causing it
> showCursor spam message issue fix

- imgui.ini
- rootex/core/renderer/rendering_device.cpp
- rootex/core/renderer/rendering_device.h
- rootex/framework/systems/physics_system.cpp
- rootex/framework/systems/render_system.cpp
> Add blending

- editor/editor.app.json
- editor/editor.cpp
- editor/editor.h
- editor/gui/viewport_dock.cpp
- game/assets/levels/flappy_bird/entities/GameText #29.entity.json
- game/assets/scripts/sound_test.lua
- game/game.app.json
- imgui.ini
- rootex/app/application.cpp
- rootex/os/os.cpp
- rootex/os/os.h
Also removes hardcoded window size
Fixes #215
> Fix viewport not scaling with monitor size

- game/assets/levels/attenuation_test/entities/Listener #5.entity.json
- game/assets/levels/attenuation_test/entities/Source #3.entity.json
- game/game.app.json
- rootex/app/application.cpp
- rootex/app/application.h
- rootex/framework/system.h
- rootex/framework/systems/audio_system.cpp
- rootex/framework/systems/audio_system.h
- rootex/framework/systems/debug_system.cpp
- rootex/framework/systems/hierarchy_system.cpp
- rootex/framework/systems/light_system.cpp
- rootex/framework/systems/serialization_system.cpp
- rootex/framework/systems/test_system.cpp
- rootex/framework/systems/ui_system.cpp
- rootex/framework/systems/ui_system.h
- rootex/os/thread.cpp
- rootex/os/thread.h
> Add threadpool to app

- editor/editor_application.cpp
- editor/editor_system.cpp
- editor/editor_system.h
- editor/gui/toolbar_dock.cpp
- game/assets/levels/attenuation_test/entities/Source #3.entity.json
- game/game.app.json
- rootex/app/application.cpp
- rootex/app/level_manager.cpp
- rootex/app/level_manager.h
- rootex/assets/materials/default.rmat
- rootex/core/audio/audio_source.cpp
- rootex/core/renderer/render_pass.h
- rootex/framework/components/visual/model_component.cpp
- rootex/framework/components/visual/model_component.h
- rootex/framework/entity_factory.cpp
- rootex/framework/entity_factory.h
- rootex/framework/system.cpp
- rootex/framework/system.h
- rootex/framework/systems/audio_system.cpp
- rootex/framework/systems/audio_system.h
- rootex/framework/systems/input_system.cpp
- rootex/framework/systems/input_system.h
- rootex/framework/systems/render_system.cpp
- rootex/framework/systems/render_system.h
- rootex/framework/systems/ui_system.cpp
- rootex/framework/systems/ui_system.h
> Fix systems turned off/not initialized per level

- editor/gui/inspector_dock.cpp
- rootex/framework/entity_factory.cpp
- rootex/framework/entity_factory.h
> add entity copying

- editor/editor_system.cpp
> Fix scene creation crash due to unconverted scene name to path

- .editorconfig
- imgui.ini
- rootex/core/resource_files/audio_resource_file.cpp
Also adds an editorconfig that helps the clang-format CI runs
> Fix multiple build warnings

- editor/gui/toolbar_dock.cpp
- editor/gui/viewport_dock.cpp
- editor/gui/viewport_dock.h
- game/assets/scenes/mesh_collision.scene.json
- imgui.ini
- rootex/app/application.cpp
- rootex/app/application.h
- rootex/core/renderer/post_processor.cpp
- rootex/core/renderer/rendering_device.cpp
- rootex/core/renderer/rendering_device.h
- rootex/framework/components/physics/physics_collider_component.cpp
- rootex/main/window.cpp
> Make Rootex window flexible

- editor/editor.app.json
- imgui.ini
- rootex/vendor/ImGuiColorTextEdit/TextEditor.cpp
The ImGui Text Editor now auto completes `(`, `{`, `[` and `"`. For example, if you type `{` it will automatically add `}`. Not a big feature, but I hope it helps 🙂
> Updated Text Editor

- imgui.ini
- rootex/core/renderer/shaders/basic_material.hlsli
- rootex/core/renderer/shaders/basic_pixel_shader.hlsl
- rootex/core/renderer/shaders/basic_vertex_shader.hlsl
- rootex/core/renderer/shaders/sky.hlsli
- rootex/core/resource_files/basic_material_resource_file.cpp
- rootex/core/resource_files/material_resource_file.h
#338 Add Fresnel Effect in all Basic shaders
> Add Fresnel Effect in all Basic Shaders

- README.md
- docs/guides/running_the_editor.rst
Added the Graphics Tools issue (`dxgidebug.dll not loaded`) and its resolution to docs.
> Add Graphics Tools issue and its resolution to docs

- editor/gui/output_dock.cpp
- editor/gui/output_dock.h
________________________
- I have added 2 buttons for filtering and clearing output. 
- The filtering button cycles from **All**, **Warning**, **Error** and shows the respected output. 
- The clear button clears the output.
> Add check boxes and button for filtering and clearing output

- .gitmodules
- README.md
- assets.bat
- Add custom URL support to script.
- Make the script work on Windows Terminal.
- Add option to clone with HTTPS as well as SSH.
> fix assets.bat and add new options

- rootex/script/interpreter.cpp
Now Lua can access Matrix Fields
> Fixed Matrix Fields in interpreter bindings
